title: "ICO Std 2002"
description: "Tianji Ranking Methodology Standard — ICO Std 2002"
baseurl: "/tianji-ranking-standard"
url: "https://ico-cloud.github.io"
theme: minima
markdown: kramdown

# 让 Jekyll 渲染所有目录
include:
  - core/
  - extensions/
  - annex/

# 排除不需要渲染的文件
exclude:
  - CHANGELOG.md
  - LICENSE
  - .gitignore
  - README.md

# 自定义变量
defaults:
  - scope:
      path: "core"
    values:
      layout: "default"
  - scope:
      path: "extensions"
    values:
      layout: "default"
  - scope:
      path: "annex"
    values:
      layout: "default"
